#! /bin/sh
# preinst script for ndn-mumble-server

set -e

if [ -f /etc/ndn-mumble-server/ndn-mumble-server.ini ] ; then
	if [ ! -f /etc/ndn-mumble-server.ini ] ; then
		echo "Moving /etc/ndn-mumble-server/ndn-mumble-server.ini to /etc/ndn-mumble-server.ini.."
		mv /etc/ndn-mumble-server/ndn-mumble-server.ini /etc/ndn-mumble-server.ini
		rmdir --ignore-fail-on-non-empty /etc/ndn-mumble-server/
		echo "Done."
	fi
fi

#DEBHELPER#

exit 0
